# Site settings
title: Leah Dickstein
email: dicksteinleah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The awesome blog of Leah Dickstein, a student of Electrical Engineering
  and Computer Science at UC Berkeley. She likes knitting, being a "foodie",
  and running.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leahdickstein.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  lahaela

# Build settings
markdown: kramdown
highlighter: pygments